/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gcurefined;
import java.util.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author timenos
 */
public class GCUbake extends javax.swing.JFrame {
    PreparedStatement pst = null;
    Connection conn = null;
    Menu run = new Menu();
    private String loggedinUser;
    private String startString;
    private String booking;
    private String SelectedRow;
    private String cancelled;
    private String query;
    

    /**
     * Creates new form GCUbake
     */
    //default constructor not used since username value has to be passed
    public GCUbake() {
        
        
    }
   
    public GCUbake(String loggedinUser){
        this.loggedinUser = loggedinUser;
        System.out.println(loggedinUser);
        initComponents();
        checkLessons();
        updateviewProgressTable();
    
    }
    private void booklesson(){
        try{

            run.getConnection();
            conn = run.con;
            startString = "beginner";

            booking = "UPDATE Lessons SET Customer='"+loggedinUser+"',lessonDate ='"+txtLessonDates.getText() +"',lessonTime ='"+ cmbLessonTimes.getSelectedItem().toString()+ "',GCU_status='"+ startString +
            "' where lessonType='"+cmbLessons_available.getSelectedItem().toString()+"';";

            pst = conn.prepareStatement(booking);
            pst.execute();

            txtLessonDates.setText("");

            JOptionPane.showMessageDialog(null, "Lesssons booked\n");
            updateviewProgressTable();
            conn.close();

        }

        catch(Exception e){

            System.err.println(e);

        }
    }
    
    
    private void updateviewProgressTable(){
        //retreives the appropriate values from the database when a lesson is booked an updates the Jtable in the viewProgress pane
        run.getConnection();
        conn = run.con;
        try{

            pst = conn.prepareStatement("SELECT * FROM Lessons where Customer='"+loggedinUser+"';");
            ResultSet rs = pst.executeQuery();
            DefaultTableModel table = (DefaultTableModel)tableCustomer.getModel();
            table.setRowCount(0);

            while(rs.next()){

                //adds in the appopriate values into the right column in tablemodel
                Object userBookings[]={rs.getInt("lessonID"), rs.getString("lessonType"), rs.getString("lessonDate"), rs.getString("lessonTime"), rs.getString("chef"), rs.getString("GCU_status")};
                table.addRow(userBookings);

            }

        }

        catch(Exception e){

            System.err.print(e);

        }
    }
   
    private void cancelLessoncustomer(){
         /* This method is used for the cancel button in the view progress pane, 
    it allows a user to cancel the lesson and updates right after that to display the value
    */
      
        run.getConnection();
        conn = run.con;
        try{
            
            SelectedRow = tableCustomer.getValueAt(tableCustomer.getSelectedRow(), 0).toString();
            cancelled = "cancelled";
            query = "UPDATE Lessons set GCU_status = '"+ cancelled +"' where lessonID ='" + SelectedRow +"';";
            
            pst = conn.prepareStatement(query);
            pst.execute();
            conn.close();
            JOptionPane.showMessageDialog(null, "Lesson cancelled");
            updateviewProgressTable();
            
        }
        
        catch(Exception e){
            System.err.print(e);
        
        
        }
        }
    
    
    private void checkLessons(){
        
        try{
        
            //retrieves the lessons that are available from the lessons table in the database and displays it for user in combobox.
            run.getConnection();
            conn = run.con;
            
            String selectQuery = "SELECT * FROM Lessons";
            pst = conn.prepareStatement(selectQuery);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
            String lessons = rs.getString("lessonType");
            cmbLessons_available.addItem(lessons);
            
            }
            }
        
        catch(Exception e){
            System.err.print(e);
        
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbLessons_available = new javax.swing.JComboBox<>();
        btnLessonbooked = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbLessonTimes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txtLessonDates = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        btnUpdateprogress = new javax.swing.JButton();
        btncancel_lesson = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        btnCustomerLogout = new javax.swing.JToggleButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Lessons available:");

        cmbLessons_available.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbLessons_available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLessons_availableActionPerformed(evt);
            }
        });

        btnLessonbooked.setFont(new java.awt.Font("Menlo", 0, 16)); // NOI18N
        btnLessonbooked.setText("Book now!");
        btnLessonbooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLessonbookedActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Available Times:");

        cmbLessonTimes.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbLessonTimes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", " " }));
        cmbLessonTimes.setToolTipText("");
        cmbLessonTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLessonTimesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Date:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("You can see which lessons are available by looking at the\ndrop-down menu next to \"Lessons available\", these are \nupdated by our chefs every day.\n\nYou can make use of the date section to fill in which date you\nwant to book your lesson.\n\nThe available times are selected in the drop down menu.\n\nWhen you are satisfied with the details, press the book now\nbutton!\n\n\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        txtLessonDates.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtLessonDates.setText("YY-MM-DD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLessonDates)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbLessons_available, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(cmbLessonTimes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLessonbooked, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbLessons_available, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLessonDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLessonTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnLessonbooked, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book Lesson", jPanel1);

        jLabel2.setText("At this page you are able to view your on-going status here at GCUbake");

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "LessonID", "Lesson", "Date", "Time", "Chef", "Status"
            }
        ));
        jScrollPane3.setViewportView(tableCustomer);

        btnUpdateprogress.setText("Update");
        btnUpdateprogress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateprogressActionPerformed(evt);
            }
        });

        btncancel_lesson.setText("Cancel lesson");
        btncancel_lesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel_lessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnUpdateprogress, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btncancel_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateprogress, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btncancel_lesson, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Progress", jPanel3);

        btnCustomerLogout.setFont(new java.awt.Font("Menlo", 0, 18)); // NOI18N
        btnCustomerLogout.setText("Logout");
        btnCustomerLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnCustomerLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(371, Short.MAX_VALUE)
                .addComponent(btnCustomerLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Logout", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLogoutActionPerformed
        JOptionPane.showMessageDialog(null, "Logged out");
        this.dispose();
        Menu run = new Menu();
        run.setVisible(true);
    }//GEN-LAST:event_btnCustomerLogoutActionPerformed

    private void btnUpdateprogressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateprogressActionPerformed

        updateviewProgressTable();
    }//GEN-LAST:event_btnUpdateprogressActionPerformed

    private void cmbLessonTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLessonTimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLessonTimesActionPerformed

    private void btnLessonbookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLessonbookedActionPerformed
        // Button for customer to book lessons use username as identifier for the bookings makes use of the booklesson method
        booklesson();
    }//GEN-LAST:event_btnLessonbookedActionPerformed

    private void cmbLessons_availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLessons_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLessons_availableActionPerformed

    private void btncancel_lessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel_lessonActionPerformed
        //cancel from customer perspective
        cancelLessoncustomer();
    }//GEN-LAST:event_btncancel_lessonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GCUbake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GCUbake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GCUbake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GCUbake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GCUbake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCustomerLogout;
    private javax.swing.JButton btnLessonbooked;
    private javax.swing.JButton btnUpdateprogress;
    private javax.swing.JToggleButton btncancel_lesson;
    private javax.swing.JComboBox<String> cmbLessonTimes;
    private javax.swing.JComboBox<String> cmbLessons_available;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTextField txtLessonDates;
    // End of variables declaration//GEN-END:variables
}
